<a href="https://colab.research.google.com/github/Leos1113/algorithmic-trading-course/blob/main/1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy

## Creación de tablas con Numpy

In [ ]:
# Importamos numpy y le asignamos un alias np para usarlo
import numpy as np

# Creamos un array de una dimension
arr = np.array([1,2,3])

# Imprimimos el array
arr

array([1, 2, 3])

In [ ]:
# Función Linspace ---> Genera valores entre un intervalo, en este caso el intervalo seria entre 0-50 y que queremos que nos genere 51 números, puede generar numeros decimales
np.linspace(0, 50, 51)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50.])

In [ ]:
# Función arrange --> Muy parecida a la anterior pero aquí solo le especificas el intervalo, numeros enteros
np.arange(0,51)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50])

In [ ]:
# Creamos un array bidimensional ---> el número de filas y columnas tiene que ser homogeneo en la matriz
arr_bidimensional = np.array([[1,2,3], [4,5,6], [7,8,9]])
arr_bidimensional

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# matriz de 0's --> le dices que te genere una matriz de 3 filas y 5 columnas
zero = np.zeros([3,5])
zero

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
# Matriz Identidad ----> Una matriz de identidad es una matriz cuadrada donde todos sus elementos son 0's menos los elementos en la diagonal principal que son 1's
identidad = np.identity(5)
identidad

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Matriz de 1's ---> genera una matriz llena de 1's del numero de filas y columnas indicados, en este caso 3 filas y 5 columnas
one = np.ones([3,5])
one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Sumar dos matrices
zero + one

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# restar dos matrices
one - zero

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
# Producto escalar
one * 10

array([[10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10.]])

In [ ]:
# Matriz aleatoria de dimension 1 con valores entre 0 y 1 (Puede servir para simular un peso aleatorio de una cartera)

random_matrix = np.random.rand(6)
random_matrix

array([0.33212069, 0.78564387, 0.1558193 , 0.36075674, 0.20031586,
       0.0226825 ])

In [ ]:
# Redimensionar una matriz de 1 dimension a 2 dimensiones (reshape)
print(f"Shape is {np.shape(random_matrix)}")

# Reshape
random_matrix = random_matrix.reshape(-1, 1) # redimensionar el array que tenemos en una sola columna, el -1 indica que nos dan igual las filas

# nueva forma
print(f"Shape is {np.shape(random_matrix)}")

random_matrix

Shape is (6,)
Shape is (6, 1)


array([[0.33212069],
       [0.78564387],
       [0.1558193 ],
       [0.36075674],
       [0.20031586],
       [0.0226825 ]])

In [ ]:
# valores aleatorios enteros
arr_int = np.random.randint(100, size=(5,5)) # generamos un array aleatorio de 5 filas y 5 columnas con números enteros entre 0 y 100
arr_int

array([[12, 85, 58, 58, 22],
       [41, 69, 53, 80, 44],
       [65, 42, 18,  7, 45],
       [53, 12, 81, 43,  0],
       [62, 76, 22, 98,  8]])

In [ ]:
# distribución normal 1 dimension


# Distribución Normal (Distribución de Gauss)

La *distribución normal*, también conocida como la *distribución de Gauss* o la *campana de Gauss*, es una de las distribuciones de probabilidad más importantes en estadísticas y matemáticas. Fue desarrollada por el matemático Carl Friedrich Gauss en el siglo XIX, aunque sus propiedades se conocían mucho antes de su trabajo.

La distribución normal es caracterizada por su forma de campana y es ampliamente utilizada en estadísticas debido a varias propiedades importantes:

1. **Simetría**: La distribución normal es simétrica alrededor de su media (promedio). Esto significa que la mitad de la distribución está a la izquierda de la media y la otra mitad está a la derecha.

2. **Media y mediana iguales**: La media y la mediana de una distribución normal son iguales, lo que indica que la mayoría de los valores se agrupan cerca de la media.

3. **Forma de campana**: La distribución normal tiene una forma de campana característica, con la mayoría de los valores cerca de la media y una disminución gradual de la probabilidad a medida que nos alejamos de la media.

4. **Parámetros**: La distribución normal está completamente definida por dos parámetros: la media (μ) y la desviación estándar (σ). La media indica el valor central o promedio, mientras que la desviación estándar mide la dispersión o la variabilidad de los datos.

5. **Teorema del límite central**: Este teorema establece que cuando se toma una muestra suficientemente grande de una población, la distribución de las medias de esas muestras se acercará a una distribución normal, independientemente de la forma de la distribución original de la población.

La ecuación que describe la función de densidad de probabilidad de una distribución normal es la siguiente:



```
f(x) = (1 / (σ * √(2π))) * e^(-((x - μ)² / (2σ²)))
```


Donde:
- `f(x)` es la densidad de probabilidad en el punto `x`.
- `μ` es la media de la distribución.
- `σ` es la desviación estándar de la distribución.
- `e` es la base del logaritmo natural (aproximadamente 2.71828).

La distribución normal es fundamental en estadísticas inferenciales y se utiliza en una variedad de aplicaciones en campos como la física, la economía, la psicología, la biología y muchas otras disciplinas para modelar y analizar datos. La comprensión de la distribución normal es esencial para muchas técnicas estadísticas y análisis de datos.


# Distribución Normal para Principiantes

La **distribución normal** es como una manera especial de agrupar números que es muy común en matemáticas y estadísticas. Aquí tienes una explicación simple para entenderla:

1. **Forma de Campana**: La distribución normal tiene una forma de "campana". Esto significa que la mayoría de los números se agrupan alrededor de un valor promedio, como las alturas de las personas en una ciudad.

2. **Promedio y Mediana**: El valor promedio en el centro de la campana es como la altura promedio de todas las personas. La mediana, que está justo en medio, es igual al promedio en una distribución normal.

3. **Dispersión**: La distribución normal también mira cuán dispersos o cercanos están los números. Si son muy parecidos, la campana es puntiaguda; si están más dispersos, la campana es más ancha.

4. **Teorema del Límite Central**: Este es un concepto importante. Dice que si tomas muchas muestras y calculas promedios, esos promedios también seguirán una distribución normal, sin importar cómo se vean los datos originales.

En resumen, la distribución normal es una forma especial de describir cómo se agrupan los números alrededor de un valor promedio en una forma de campana, y se utiliza para comprender y analizar datos en muchas áreas, desde la física hasta la economía y la biología. Es una herramienta poderosa en estadísticas que nos ayuda a entender el mundo que nos rodea.


